/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DidatticaRouteImport } from './routes/didattica'
import { Route as CvRouteImport } from './routes/cv'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as ChiSonoRouteImport } from './routes/chi-sono'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DidatticaIndexRouteImport } from './routes/didattica.index'
import { Route as ChiSonoIndexRouteImport } from './routes/chi-sono.index'
import { Route as DidatticaLezioniRouteImport } from './routes/didattica.lezioni'
import { Route as DidatticaFormulariRouteImport } from './routes/didattica.formulari'
import { Route as DidatticaEsercitazioniRouteImport } from './routes/didattica.esercitazioni'
import { Route as DidatticaCalcolatoriRouteImport } from './routes/didattica.calcolatori'
import { Route as DidatticaAppuntiRouteImport } from './routes/didattica.appunti'
import { Route as ChiSonoProgettiRouteImport } from './routes/chi-sono.progetti'
import { Route as ChiSonoFormazioneRouteImport } from './routes/chi-sono.formazione'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DidatticaRoute = DidatticaRouteImport.update({
  id: '/didattica',
  path: '/didattica',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiSonoRoute = ChiSonoRouteImport.update({
  id: '/chi-sono',
  path: '/chi-sono',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DidatticaIndexRoute = DidatticaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DidatticaRoute,
} as any)
const ChiSonoIndexRoute = ChiSonoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChiSonoRoute,
} as any)
const DidatticaLezioniRoute = DidatticaLezioniRouteImport.update({
  id: '/lezioni',
  path: '/lezioni',
  getParentRoute: () => DidatticaRoute,
} as any)
const DidatticaFormulariRoute = DidatticaFormulariRouteImport.update({
  id: '/formulari',
  path: '/formulari',
  getParentRoute: () => DidatticaRoute,
} as any)
const DidatticaEsercitazioniRoute = DidatticaEsercitazioniRouteImport.update({
  id: '/esercitazioni',
  path: '/esercitazioni',
  getParentRoute: () => DidatticaRoute,
} as any)
const DidatticaCalcolatoriRoute = DidatticaCalcolatoriRouteImport.update({
  id: '/calcolatori',
  path: '/calcolatori',
  getParentRoute: () => DidatticaRoute,
} as any)
const DidatticaAppuntiRoute = DidatticaAppuntiRouteImport.update({
  id: '/appunti',
  path: '/appunti',
  getParentRoute: () => DidatticaRoute,
} as any)
const ChiSonoProgettiRoute = ChiSonoProgettiRouteImport.update({
  id: '/progetti',
  path: '/progetti',
  getParentRoute: () => ChiSonoRoute,
} as any)
const ChiSonoFormazioneRoute = ChiSonoFormazioneRouteImport.update({
  id: '/formazione',
  path: '/formazione',
  getParentRoute: () => ChiSonoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chi-sono': typeof ChiSonoRouteWithChildren
  '/contatti': typeof ContattiRoute
  '/cv': typeof CvRoute
  '/didattica': typeof DidatticaRouteWithChildren
  '/login': typeof LoginRoute
  '/chi-sono/formazione': typeof ChiSonoFormazioneRoute
  '/chi-sono/progetti': typeof ChiSonoProgettiRoute
  '/didattica/appunti': typeof DidatticaAppuntiRoute
  '/didattica/calcolatori': typeof DidatticaCalcolatoriRoute
  '/didattica/esercitazioni': typeof DidatticaEsercitazioniRoute
  '/didattica/formulari': typeof DidatticaFormulariRoute
  '/didattica/lezioni': typeof DidatticaLezioniRoute
  '/chi-sono/': typeof ChiSonoIndexRoute
  '/didattica/': typeof DidatticaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contatti': typeof ContattiRoute
  '/cv': typeof CvRoute
  '/login': typeof LoginRoute
  '/chi-sono/formazione': typeof ChiSonoFormazioneRoute
  '/chi-sono/progetti': typeof ChiSonoProgettiRoute
  '/didattica/appunti': typeof DidatticaAppuntiRoute
  '/didattica/calcolatori': typeof DidatticaCalcolatoriRoute
  '/didattica/esercitazioni': typeof DidatticaEsercitazioniRoute
  '/didattica/formulari': typeof DidatticaFormulariRoute
  '/didattica/lezioni': typeof DidatticaLezioniRoute
  '/chi-sono': typeof ChiSonoIndexRoute
  '/didattica': typeof DidatticaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chi-sono': typeof ChiSonoRouteWithChildren
  '/contatti': typeof ContattiRoute
  '/cv': typeof CvRoute
  '/didattica': typeof DidatticaRouteWithChildren
  '/login': typeof LoginRoute
  '/chi-sono/formazione': typeof ChiSonoFormazioneRoute
  '/chi-sono/progetti': typeof ChiSonoProgettiRoute
  '/didattica/appunti': typeof DidatticaAppuntiRoute
  '/didattica/calcolatori': typeof DidatticaCalcolatoriRoute
  '/didattica/esercitazioni': typeof DidatticaEsercitazioniRoute
  '/didattica/formulari': typeof DidatticaFormulariRoute
  '/didattica/lezioni': typeof DidatticaLezioniRoute
  '/chi-sono/': typeof ChiSonoIndexRoute
  '/didattica/': typeof DidatticaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chi-sono'
    | '/contatti'
    | '/cv'
    | '/didattica'
    | '/login'
    | '/chi-sono/formazione'
    | '/chi-sono/progetti'
    | '/didattica/appunti'
    | '/didattica/calcolatori'
    | '/didattica/esercitazioni'
    | '/didattica/formulari'
    | '/didattica/lezioni'
    | '/chi-sono/'
    | '/didattica/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contatti'
    | '/cv'
    | '/login'
    | '/chi-sono/formazione'
    | '/chi-sono/progetti'
    | '/didattica/appunti'
    | '/didattica/calcolatori'
    | '/didattica/esercitazioni'
    | '/didattica/formulari'
    | '/didattica/lezioni'
    | '/chi-sono'
    | '/didattica'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chi-sono'
    | '/contatti'
    | '/cv'
    | '/didattica'
    | '/login'
    | '/chi-sono/formazione'
    | '/chi-sono/progetti'
    | '/didattica/appunti'
    | '/didattica/calcolatori'
    | '/didattica/esercitazioni'
    | '/didattica/formulari'
    | '/didattica/lezioni'
    | '/chi-sono/'
    | '/didattica/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChiSonoRoute: typeof ChiSonoRouteWithChildren
  ContattiRoute: typeof ContattiRoute
  CvRoute: typeof CvRoute
  DidatticaRoute: typeof DidatticaRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/didattica': {
      id: '/didattica'
      path: '/didattica'
      fullPath: '/didattica'
      preLoaderRoute: typeof DidatticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-sono': {
      id: '/chi-sono'
      path: '/chi-sono'
      fullPath: '/chi-sono'
      preLoaderRoute: typeof ChiSonoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/didattica/': {
      id: '/didattica/'
      path: '/'
      fullPath: '/didattica/'
      preLoaderRoute: typeof DidatticaIndexRouteImport
      parentRoute: typeof DidatticaRoute
    }
    '/chi-sono/': {
      id: '/chi-sono/'
      path: '/'
      fullPath: '/chi-sono/'
      preLoaderRoute: typeof ChiSonoIndexRouteImport
      parentRoute: typeof ChiSonoRoute
    }
    '/didattica/lezioni': {
      id: '/didattica/lezioni'
      path: '/lezioni'
      fullPath: '/didattica/lezioni'
      preLoaderRoute: typeof DidatticaLezioniRouteImport
      parentRoute: typeof DidatticaRoute
    }
    '/didattica/formulari': {
      id: '/didattica/formulari'
      path: '/formulari'
      fullPath: '/didattica/formulari'
      preLoaderRoute: typeof DidatticaFormulariRouteImport
      parentRoute: typeof DidatticaRoute
    }
    '/didattica/esercitazioni': {
      id: '/didattica/esercitazioni'
      path: '/esercitazioni'
      fullPath: '/didattica/esercitazioni'
      preLoaderRoute: typeof DidatticaEsercitazioniRouteImport
      parentRoute: typeof DidatticaRoute
    }
    '/didattica/calcolatori': {
      id: '/didattica/calcolatori'
      path: '/calcolatori'
      fullPath: '/didattica/calcolatori'
      preLoaderRoute: typeof DidatticaCalcolatoriRouteImport
      parentRoute: typeof DidatticaRoute
    }
    '/didattica/appunti': {
      id: '/didattica/appunti'
      path: '/appunti'
      fullPath: '/didattica/appunti'
      preLoaderRoute: typeof DidatticaAppuntiRouteImport
      parentRoute: typeof DidatticaRoute
    }
    '/chi-sono/progetti': {
      id: '/chi-sono/progetti'
      path: '/progetti'
      fullPath: '/chi-sono/progetti'
      preLoaderRoute: typeof ChiSonoProgettiRouteImport
      parentRoute: typeof ChiSonoRoute
    }
    '/chi-sono/formazione': {
      id: '/chi-sono/formazione'
      path: '/formazione'
      fullPath: '/chi-sono/formazione'
      preLoaderRoute: typeof ChiSonoFormazioneRouteImport
      parentRoute: typeof ChiSonoRoute
    }
  }
}

interface ChiSonoRouteChildren {
  ChiSonoFormazioneRoute: typeof ChiSonoFormazioneRoute
  ChiSonoProgettiRoute: typeof ChiSonoProgettiRoute
  ChiSonoIndexRoute: typeof ChiSonoIndexRoute
}

const ChiSonoRouteChildren: ChiSonoRouteChildren = {
  ChiSonoFormazioneRoute: ChiSonoFormazioneRoute,
  ChiSonoProgettiRoute: ChiSonoProgettiRoute,
  ChiSonoIndexRoute: ChiSonoIndexRoute,
}

const ChiSonoRouteWithChildren =
  ChiSonoRoute._addFileChildren(ChiSonoRouteChildren)

interface DidatticaRouteChildren {
  DidatticaAppuntiRoute: typeof DidatticaAppuntiRoute
  DidatticaCalcolatoriRoute: typeof DidatticaCalcolatoriRoute
  DidatticaEsercitazioniRoute: typeof DidatticaEsercitazioniRoute
  DidatticaFormulariRoute: typeof DidatticaFormulariRoute
  DidatticaLezioniRoute: typeof DidatticaLezioniRoute
  DidatticaIndexRoute: typeof DidatticaIndexRoute
}

const DidatticaRouteChildren: DidatticaRouteChildren = {
  DidatticaAppuntiRoute: DidatticaAppuntiRoute,
  DidatticaCalcolatoriRoute: DidatticaCalcolatoriRoute,
  DidatticaEsercitazioniRoute: DidatticaEsercitazioniRoute,
  DidatticaFormulariRoute: DidatticaFormulariRoute,
  DidatticaLezioniRoute: DidatticaLezioniRoute,
  DidatticaIndexRoute: DidatticaIndexRoute,
}

const DidatticaRouteWithChildren = DidatticaRoute._addFileChildren(
  DidatticaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChiSonoRoute: ChiSonoRouteWithChildren,
  ContattiRoute: ContattiRoute,
  CvRoute: CvRoute,
  DidatticaRoute: DidatticaRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
