/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RicercaRouteImport } from './routes/ricerca'
import { Route as ProgettiRouteImport } from './routes/progetti'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FormazioneRouteImport } from './routes/formazione'
import { Route as DidatticaRouteImport } from './routes/didattica'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as ChiSonoRouteImport } from './routes/chi-sono'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const RicercaRoute = RicercaRouteImport.update({
  id: '/ricerca',
  path: '/ricerca',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgettiRoute = ProgettiRouteImport.update({
  id: '/progetti',
  path: '/progetti',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FormazioneRoute = FormazioneRouteImport.update({
  id: '/formazione',
  path: '/formazione',
  getParentRoute: () => rootRouteImport,
} as any)
const DidatticaRoute = DidatticaRouteImport.update({
  id: '/didattica',
  path: '/didattica',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiSonoRoute = ChiSonoRouteImport.update({
  id: '/chi-sono',
  path: '/chi-sono',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chi-sono': typeof ChiSonoRoute
  '/contatti': typeof ContattiRoute
  '/didattica': typeof DidatticaRoute
  '/formazione': typeof FormazioneRoute
  '/login': typeof LoginRoute
  '/progetti': typeof ProgettiRoute
  '/ricerca': typeof RicercaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chi-sono': typeof ChiSonoRoute
  '/contatti': typeof ContattiRoute
  '/didattica': typeof DidatticaRoute
  '/formazione': typeof FormazioneRoute
  '/login': typeof LoginRoute
  '/progetti': typeof ProgettiRoute
  '/ricerca': typeof RicercaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chi-sono': typeof ChiSonoRoute
  '/contatti': typeof ContattiRoute
  '/didattica': typeof DidatticaRoute
  '/formazione': typeof FormazioneRoute
  '/login': typeof LoginRoute
  '/progetti': typeof ProgettiRoute
  '/ricerca': typeof RicercaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chi-sono'
    | '/contatti'
    | '/didattica'
    | '/formazione'
    | '/login'
    | '/progetti'
    | '/ricerca'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/chi-sono'
    | '/contatti'
    | '/didattica'
    | '/formazione'
    | '/login'
    | '/progetti'
    | '/ricerca'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chi-sono'
    | '/contatti'
    | '/didattica'
    | '/formazione'
    | '/login'
    | '/progetti'
    | '/ricerca'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChiSonoRoute: typeof ChiSonoRoute
  ContattiRoute: typeof ContattiRoute
  DidatticaRoute: typeof DidatticaRoute
  FormazioneRoute: typeof FormazioneRoute
  LoginRoute: typeof LoginRoute
  ProgettiRoute: typeof ProgettiRoute
  RicercaRoute: typeof RicercaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ricerca': {
      id: '/ricerca'
      path: '/ricerca'
      fullPath: '/ricerca'
      preLoaderRoute: typeof RicercaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progetti': {
      id: '/progetti'
      path: '/progetti'
      fullPath: '/progetti'
      preLoaderRoute: typeof ProgettiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formazione': {
      id: '/formazione'
      path: '/formazione'
      fullPath: '/formazione'
      preLoaderRoute: typeof FormazioneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/didattica': {
      id: '/didattica'
      path: '/didattica'
      fullPath: '/didattica'
      preLoaderRoute: typeof DidatticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-sono': {
      id: '/chi-sono'
      path: '/chi-sono'
      fullPath: '/chi-sono'
      preLoaderRoute: typeof ChiSonoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChiSonoRoute: ChiSonoRoute,
  ContattiRoute: ContattiRoute,
  DidatticaRoute: DidatticaRoute,
  FormazioneRoute: FormazioneRoute,
  LoginRoute: LoginRoute,
  ProgettiRoute: ProgettiRoute,
  RicercaRoute: RicercaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
